### ISSUE TITLE
Request: Allow transport rides to remain free

### ISSUE THREAD

**Issue by Fred-1044276** [mgovea/openrct2-ride-price-manager#1]
I just got this plugin and all I need to say is, this plugin is making my OpenRCT2 gameplay better. However, I do use transport rides quite often and I always make them free entry so that guests will ride them no matter what. This plugin, if activated, automatically sets prices on all transport rides, and I have to disable the plugin and manually set all the transport rides to free. I'd like to request a change to this plugin such that even when it's activated, all transport rides remain free too.

**Comment by Fred-1044276** [comment]
So I open an issue about this, and I get no response from @mgovea ? It would be better if someone stepped in and fixed the plugin to the way I want it, even if that means I may have to do it myself.

**Comment by mgovea** [comment]
As I put in the review of Sadret's changes, I haven't have access to my windows machine due to a move, so I'm grateful that he made the changes. Sorry for leaving you in the dark.

**Comment by mgovea** [comment]
@Sadret mostly addressed this in #3 , and I made that behavior default in #5 .
You'll have to manually set the prices to free, but that's a good start.
