### ISSUE TITLE
Updated prices are not synced in multiplayer

### ISSUE THREAD

**Issue by saeltz** [mgovea/openrct2-ride-price-manager#37]
Thanks for this great plugin!

**Problem**
I saw that you haven't tested the plugin against multiplayer. I tried it today and can confirm that it still works if the person hosting the game has it installed. The prices are not synced to the other players, though.

**Solution**
I don't know if it's possible but at best the plugin could allow for syncing prices in multiplayer. Manual prices are already synced.

**Alternatives**
Alternatively, it could be possible to run the plugin on all clients. That's not possible at the moment.

**Additional context**
Tested with OpenRCT2 0.3.2 on Mac and Ubuntu.

**Comment by kscheel** [comment]
multiplayer functionality would really be great! :)

**Comment by mgovea** [comment]
Check out #111 (and #113 oof) and https://github.com/mgovea/openrct2-ride-price-manager/releases/tag/1.3.0
I didn't test if MP works, but it should. Let me know if we can close.

Also, there's no permissions, so grief wisely. If you have a use case that requires permissions, I might think about doing that... no promises.

**Comment by kscheel** [comment]
it throws an error on my headless server:

`[Ride Price Manager] ReferenceError: identifier 'ui' undefined`

But everything seems to work fine anyway :) Thank you!

**Comment by mgovea** [comment]
Sweet. I'm calling this done. I did open #113 to investigate your error though.
