### ISSUE TITLE
Bug: Plugin sets Ride prices even when they can't be set using the UI

### ISSUE THREAD

**Issue by gfrewqpoiu** [mgovea/openrct2-ride-price-manager#4]
As mentioned in [this issue](https://github.com/OpenRCT2/OpenRCT2/issues/12818) in the Open RCT 2 Project, the Plugin API doesn't prevent the Plugin from setting prices on rides, even when the ride is a Pay for Entry / Free Rides scenario.
I played a round of Amity Airfield, and even though my entrance price was very reasonable (30€ for a park with 3 Coasters and 5 Flatrides) I constantly got messages that my park entrance fee was way too high, no guests were spawning without advertising and I got the worst value park award two times in a row.
I would really enjoy it if the plugin would disable itself in these scenarios or  if it got a checkbox that disabled the plugin and set all prices to Free to "reset" the modified prices in these scenarios (which the user can't reset using the GUI)

**Comment by mgovea** [comment]
Last time I checked, there was no way to read the current park admission price or the scenario rules (free admission vs. free rides vs. charge for both), so I can't fully address this issue without an update in the plugin API.

I requested the ability to read the scenario rules in [issue 11759](https://github.com/OpenRCT2/OpenRCT2/issues/11759).

I see the problem that the plugin instantly updates all prices on load that was introduced in https://github.com/mgovea/openrct2-ride-price-manager/pull/3 - this prevents the player from disabling the plugin before it sets prices upon loading a scenario.

**Comment by gfrewqpoiu** [comment]
Yeah, that is why I suggested the option to use the same "bug" to reset the ride prices back to Free so that if you forgot you had the plugin on, you can at least reset the prices again and keep playing.

But I hope they expand the API so that is no longer an issue in the future.

**Comment by mgovea** [comment]
I set the default of "ignore free rides" to `true`, so this should be ok by default.
A few people may have issues if they toggled that setting, but the newest version should be ok.

I still can't 100% solve this problem without that api change I mentioned above, but I think it's worth closing for now.

**Comment by chess123mate** [comment]
With https://github.com/OpenRCT2/OpenRCT2/pull/12832 merged, this should no longer be a problem.
